name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Pull latest code
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd /opt/HypersonicVehicles-PreLandingSimulator
          git checkout main
          git fetch https://x-access-token:${GITHUB_TOKEN}@github.com/yl-space/HypersonicVehicles-PreLandingSimulator.git main
          git reset --hard origin/main
          git pull
      - name: Rebuild and restart services
        run: |
          cd /opt/HypersonicVehicles-PreLandingSimulator
          docker compose build --pull
          docker compose up -d
