name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Pull latest code
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd /opt/HypersonicVehicles-PreLandingSimulator/mars-edl-simulation
          git checkout main
          git pull https://x-access-token:${GITHUB_TOKEN}@github.com/Sonica-B/HypersonicVehicles-PreLandingSimulator.git main
      - name: Rebuild and restart services
        run: |
          cd /opt/HypersonicVehicles-PreLandingSimulator/mars-edl-simulation
          docker compose build --pull
          docker compose up -d